### ISSUE TITLE
Null response

### ISSUE THREAD

**Issue by jchannon** [JChapman202/siren-crawler#4]
Hi, I just ran the live demo at http://sirencrawler.altervista.org/ and no matter what url i put in, it always displayed null as the response. any ideas?

**Comment by JChapman202** [comment]
Hey Jonathan.  Are you running a server that responds with Siren somewhere?  The current UI will respond null if it does not receive a response from the server or if the server responds with an error.  For a more detailed response at this time I would look at the chrome dev tools to see exactly what response the server is sending back.

**Comment by jchannon** [comment]
Yeah I tried that and it seemed empty.  I am running a server with a siren response, double checked with postman

**Comment by jchannon** [comment]
Screenshot : postman shows a response

Siren crawler shows a 200 but no response data  

<img width="1915" alt="screen shot 2016-06-16 at 13 23 38" src="https://cloud.githubusercontent.com/assets/105126/16116571/a33b4384-33c5-11e6-9eca-d77533a8ee83.png">

**Comment by JChapman202** [comment]
It seems strange if that is returning a 200 response.  I can't actually tell from the chrome dev tools.  However, my guess would be that your server does not support CORS (Cross origin resource sharing).  Since SirenCrawler is hosted within a browser it will appear as a cross origin request.  It should actually be performing a OPTION query first to the URL you entered to see if it supports CORS, and only upon successful OPTION should it then perform the GET you requested to load the siren data.

Do you know for sure that CORS is available on your server?  If not, can you add it?  Or at least add the sirencrawler.altervista.org URL as a trusted origin?

**Comment by jchannon** [comment]
Aha! CORS was the solution.

Thanks for the help!

Also just a "high five" for this work, there is so much emphasis on writing
Hypermedia APIs but nothing on clients so great job, thanks!!
